# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.CharField(max_length=200)),
                ('IP', models.CharField(default=b'0.0.0.0', max_length=16)),
                ('available', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
