# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='target_text',
        ),
        migrations.AddField(
            model_name='target',
            name='IPSS_version',
            field=models.CharField(default=b'0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='OS',
            field=models.CharField(default=b'0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='bios',
            field=models.CharField(default=b'0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='name',
            field=models.CharField(default=b'NoName', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
