# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171124_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='platform',
            field=models.CharField(default=b'NoPlatform', max_length=50),
        ),
    ]
