# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_target_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.CharField(default=b'NotConnected', max_length=16),
        ),
    ]
