# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171124_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='ports',
            field=models.CharField(default=b'No Ports', max_length=1000),
        ),
    ]
