# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_target_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='system_information_js',
            field=models.CharField(default=b'No Data', max_length=1000),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(default=b'No Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='platform',
            field=models.CharField(default=b'No Platform', max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.CharField(default=b'Not Connected', max_length=16),
        ),
    ]
