# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171128_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='CPHSKU',
            field=models.CharField(default=b'No SKu', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='CPHid',
            field=models.CharField(default=b'No id', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='CPHplatform',
            field=models.CharField(default=b'No Platform', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='CPHstepping',
            field=models.CharField(default=b'No Stepping', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='CPUSKU',
            field=models.CharField(default=b'No SKu', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='CPUid',
            field=models.CharField(default=b'No id', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='CPUplatform',
            field=models.CharField(default=b'No Platform', max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='CPUstepping',
            field=models.CharField(default=b'No Stepping', max_length=50),
        ),
    ]
