# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20171130_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'no interface', max_length=15)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Target')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=b'-1', max_length=10)),
                ('speed', models.CharField(default=b'0', max_length=50)),
                ('width', models.CharField(default=b'0', max_length=50)),
                ('state', models.CharField(default=b'no data', max_length=50)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Interface')),
            ],
        ),
    ]
